# for production use
services:

  portainer:
    container_name: umn-cts-portainer
    image: portainer/portainer-ce:2.25.1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/portainer-data:/data
    ports:
      - "9000:9000"

  nginx-proxy-manager:
    container_name: umn-cts-nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:2.12.2'
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:81:81"
      - "0.0.0.0:443:443"
    volumes:
      - ./data/nginx-proxy-manager-data:/data
      - ./data/letsencrypt:/etc/letsencrypt
    environment:
      INITIAL_ADMIN_EMAIL: ${NPM_INITIAL_ADMIN_EMAIL:-admin@admin.com}
      INITIAL_ADMIN_PASSWORD: ${NPM_INITIAL_ADMIN_PASSWORD:-umncts}


  # watchtower used to automatically update docker images when newer versions are available
  watchtower:
    container_name: umn-cts-watchtower
    image: containrrr/watchtower:1.7.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: unless-stopped

  grafana:
    container_name: umn-cts-grafana
    image: grafana/grafana:11.5.2
    ports:
      - "3050:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-grafana}
    depends_on:
      - loki
    volumes:
      - ./data/grafana-data:/var/lib/grafana
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh

  loki:
    container_name: umn-cts-loki
    image: grafana/loki:3.3.2
    user: root
    ports:
      - "3100:3100"
    volumes:
      - ./data/loki-data:/loki
      - ./config/loki-config.yaml:/etc/loki/config.yaml

  promtail:
    container_name: umn-cts-promtail
    image: grafana/promtail:2.7.1
    volumes:
      - /data/nginx-proxy-manager-data/nginx/logs/:/var/log # path to your NPM logs
      - ./config/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

networks:
  default:
    external: true
    name: ${NETWORK_NAME:-nginx-proxy-manager-network}
